name: Build

on:
  workflow_dispatch:
    inputs:
      remote_ref:
        description: 'Remote reference'
        required: true
        default: 'master'
      local_ref:
        description: 'Local reference'
        required: true
        default: 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      with:
        fetch-depth: 0

    - name: Install
      run: |
        sudo apt-get update
        sudo apt-get install wget tar cmake ninja-build clang python3 build-essential libpthread-stubs0-dev clang-11 gcc-multilib lld
        sudo apt-get install git cmake ccache python3 ninja-build nasm yasm gawk lsb-release wget software-properties-common gnupg
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
        sudo apt-get install software-properties-common
        sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

    - name: Git
      run: |
        git clone https://github.com/ClickHouse/ClickHouse.git
        cd ClickHouse
        git checkout ${{ github.event.inputs.remote_ref }}
        git submodule init
        git submodule update

    - name: Build
      run: |
        export CC=clang-16
        export CXX=clang++-16
        cd ClickHouse
        mkdir build
        cmake -S . -B build
        cmake --build build  # or: `cd build; ninja`
